# ONLY local development with docker
services:
  db:
    image: 'postgres'
    container_name: postgres_todo
    environment:
      - POSTGRES_DB=todo_database
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_password
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./db-insert.sql:/docker-entrypoint-initdb.d/02-data.sql:ro